// Per-team reference for the Sweepstakes detail view.
// FIFA rankings are factual; the summary/strengths/weaknesses are paraphrased
// in original wording (not copied) from the Guardian's WC2026 player guide.
export const teamInfo = {
  "Mexico": { fifaRank: 15,
    summary: "Co-hosts at a third World Cup: adaptable and competitive, but carrying heavy home expectations.",
    strengths: "Flexible tactics, a compact defence and a game built on intensity, aggressive pressing and quick transitions.",
    weaknesses: "Co-host pressure can tell even on experienced heads, and the pragmatic approach has its critics." },
  "South Africa": { fifaRank: 60,
    summary: "Bafana Bafana have shaken off a stagnant spell, edging out Nigeria to qualify.",
    strengths: "A revitalised national setup knitted together by Mokoena in midfield and built on well-drilled teamwork.",
    weaknesses: "A largely home-based squad lacks broad experience and leans on counterattacks for chances." },
  "South Korea": { fifaRank: 25,
    summary: "Unbeaten in qualifying for an 11th straight finals, though ambitions rarely stretch past the group.",
    strengths: "A robust core, strong spirit and a genuine talisman in former Premier League Golden Boot winner Son.",
    weaknesses: "Uncertainty over the best formation after a late switch to 3-4-3, plus form and fitness doubts over key men." },
  "Czechia": { fifaRank: 41,
    summary: "Play-off qualifiers with a disciplined, well-organised setup and hopes of escaping a moderate group.",
    strengths: "An experienced backbone anchored by Soucek in midfield, plus Schick's 16-goal Bundesliga season up front.",
    weaknesses: "Short on technical creativity, leaning heavily on physicality, work rate and set-piece threat." },
  "Canada": { fifaRank: 30,
    summary: "Co-hosts turned into a solid, settled side with a developing mentality for pressure.",
    strengths: "A consistent 4-4-2 pressing from the front with pace out wide, backed by a resilient defence.",
    weaknesses: "Fitness worries over Davies, a tough group and the weight of never having won a World Cup match." },
  "Bosnia-Herzegovina": { fifaRank: 64,
    summary: "Surprise qualifiers who knocked out Italy in the play-offs — intense and unpredictable enough to win neutrals over.",
    strengths: "Aggressive defending, direct and passionate football, quick transitions and a huge young talent in Alajbegovic.",
    weaknesses: "That intensity can tip into lost shape and discipline, and dominating games in this group looks unlikely." },
  "Qatar": { fifaRank: 55,
    summary: "The 2022 hosts stumbled through qualifying but may benefit from a far lower profile this time.",
    strengths: "A clear focus on absorbing pressure and hitting opponents on the break.",
    weaknesses: "A leaky qualifying defence (24 conceded in 10 games) and preparation badly disrupted by regional conflict." },
  "Switzerland": { fifaRank: 19,
    summary: "Aiming for their best-ever World Cup, hoping to turn dependable regulars into genuine contenders.",
    strengths: "Comfortable group-topping qualifiers blending experience and fresh talent around Xhaka.",
    weaknesses: "Some uncertainty over formation and big fan expectations despite limited depth beyond the first XI." },
  "Brazil": { fifaRank: 6,
    summary: "Five-time winners chasing an end to years of underachievement with a newly attack-minded side.",
    strengths: "Built around Vinicius, a solid spine with licence for attacking flair in an aggressive 4-2-4.",
    weaknesses: "Full-backs short of former greats, and a 34-year-old Neymar whose injuries may limit his impact." },
  "Morocco": { fifaRank: 7,
    summary: "Africa's first-ever semi-finalists in 2022, expecting another deep run after a coaching change.",
    strengths: "A setup that frees star man Hakimi, with belief boosted by reaching the last four in Qatar.",
    weaknesses: "Wobbled under pressure as Afcon hosts and will face close scrutiny again." },
  "Haiti": { fifaRank: 82,
    summary: "Group outsiders reaching their first World Cup since 1974 despite turmoil at home.",
    strengths: "A disciplined side with the pace and skill to counter, with Bellegarde and Isidor offering proven quality.",
    weaknesses: "Instability has hampered preparation, with striker Nazon held up in Iran." },
  "Scotland": { fifaRank: 43,
    summary: "Ended a 28-year wait to qualify and now chase a first-ever trip to the knockouts.",
    strengths: "An organised, hugely experienced first-choice XI built around McTominay and Robertson.",
    weaknesses: "No reliable goalscorer, a cautious streak, and Gilmour's injury thinning an already shallow squad." },
  "United States": { fifaRank: 16,
    summary: "Co-hosts with low expectations after a turbulent buildup, but a route to the latter stages exists.",
    strengths: "A core of experienced 'glue guys' and a coach who knows how to win knockout games.",
    weaknesses: "Lingering uncertainty over the best team and setup has frustrated home fans." },
  "Paraguay": { fifaRank: 40,
    summary: "Back after 12 years, rebuilt around intensity and clean sheets with real hopes of progress.",
    strengths: "A physical style with the tenacity to grind out unlikely results, as in qualifying.",
    weaknesses: "Among the lowest scorers in Conmebol qualifying, with heavy reliance on Enciso to create." },
  "Australia": { fifaRank: 27,
    summary: "At a sixth straight finals with an experienced core, young attacking talent and eyes on a first knockout win.",
    strengths: "Tougher to beat after an improved qualifying campaign, with Irankunda leading a dangerous counter.",
    weaknesses: "A transitional squad short on big names, still shaking off the underdog tag." },
  "Türkiye": { fifaRank: 22,
    summary: "Back on the big stage after a 22-year absence, with a talented squad primed to make an impact.",
    strengths: "A harmonious group with in-form players and two of Europe's brightest talents in Guler and Yildiz.",
    weaknesses: "No proven striker and patchy big-game experience, raising the risk of an Euro 2020-style collapse." },
  "Germany": { fifaRank: 10,
    summary: "2014 winners rebuilt after back-to-back group exits, now better organised.",
    strengths: "A blend of rising stars and stalwarts with ample creativity to exploit a kind group draw.",
    weaknesses: "Not yet vintage and inconsistent, with Neuer recalled after no successor emerged." },
  "Curaçao": { fifaRank: 83,
    summary: "The smallest nation ever, by population and area, to reach a World Cup — aiming to make a splash.",
    strengths: "A vastly experienced returning coach, steady improvement and recruits from the island's diaspora.",
    weaknesses: "A possession style that may need rethinking in a tough group, opening against Germany." },
  "Côte d'Ivoire": { fifaRank: 34,
    summary: "The Elephants believe they can finally reach the knockouts — and maybe more.",
    strengths: "A settled, flexible defence that didn't concede in qualifying, plus plenty of attacking options.",
    weaknesses: "Midfield selection questions and an underwhelming Afcon defence have lowered expectations." },
  "Ecuador": { fifaRank: 24,
    summary: "At a fifth World Cup with arguably their strongest squad, chasing a first knockout win.",
    strengths: "A miserly defence (five conceded in 18 qualifiers) marshalled by Pacho and Hincapie, plus a high-pressing identity.",
    weaknesses: "Scoring is a worry; beyond veteran Enner Valencia the attack is talented but raw." },
  "Netherlands": { fifaRank: 8,
    summary: "Set a semi-final target but forced to favour strength and fitness over flair amid injuries.",
    strengths: "Unbeaten, 27-goal qualifiers whose back four, led by Van Dijk, looks the standout.",
    weaknesses: "Several key men short of minutes or returning from injury, with a tricky opener against Japan." },
  "Japan": { fifaRank: 18,
    summary: "Perennial dark horses eyeing new ground with a run to the quarter-finals.",
    strengths: "A cohesive, front-foot pressing unit with the depth now to go deeper.",
    weaknesses: "Mitoma's injury is a blow, and a tough group of three physical, experienced sides awaits." },
  "Sweden": { fifaRank: 38,
    summary: "Salvaged a poor campaign via the play-offs and have the attacking talent to go further.",
    strengths: "Two elite finishers up front, balanced by a hard-working back five.",
    weaknesses: "Isak endured a grim first Liverpool season and the new approach has had little bedding-in time." },
  "Tunisia": { fifaRank: 46,
    summary: "Six World Cups, six group exits — now seeking a breakthrough with a diaspora-rich squad.",
    strengths: "Didn't concede in qualifying, tactically flexible and willing to blood young talent.",
    weaknesses: "Creativity rests heavily on Mejbri in a low-key side short on elite experience." },
  "Belgium": { fifaRank: 9,
    summary: "A transitional Red Devils side that qualified smoothly if unspectacularly.",
    strengths: "Real attacking edge in De Bruyne, Doku and Lukaku.",
    weaknesses: "Defence (Courtois aside) is the weak spot now the golden generation has moved on." },
  "Egypt": { fifaRank: 29,
    summary: "Salah drove qualifying, but Afcon exposed the side's limits with a semi-final loss to Senegal.",
    strengths: "Cohesive, hard to break down and emotionally committed.",
    weaknesses: "Can look blunt when Salah is doubled up and the midfield can't beat the press." },
  "Iran": { fifaRank: 21,
    summary: "Smooth in qualifying, far less so since; involvement was even in doubt amid conflict with the US.",
    strengths: "Tactically adaptable, mixing shapes like 3-6-1 and 4-4-2 in recent friendlies.",
    weaknesses: "Off-pitch disruption to manage, based in Mexico but playing three group games in the US." },
  "New Zealand": { fifaRank: 85,
    summary: "The lowest-ranked team here, but a squad that has grown from part-timers into professionals.",
    strengths: "Plenty of belief in camp that they can reach the knockouts for the first time.",
    weaknesses: "Star striker Wood has had an injury-hit year and recent form is mixed." },
  "Spain": { fifaRank: 2,
    summary: "Rightly among the favourites, blending youth and experience with prodigious talent.",
    strengths: "Yamal and Williams add freshness to a ball-dominant side with a fearsome frontline.",
    weaknesses: "Few — the back four can wobble, but this is a fiercely united team." },
  "Cape Verde": { fifaRank: 68,
    summary: "An eclectic group of Blue Sharks in uncharted waters on their World Cup debut.",
    strengths: "A squad settled for half a decade, physical and defensively willing but with technical forwards too.",
    weaknesses: "Key defender Logan Costa has missed the whole season with a cruciate injury." },
  "Saudi Arabia": { fifaRank: 61,
    summary: "A chaotic buildup, with a new coach installed in April after a bitter departure.",
    strengths: "Low expectations ease the pressure; expect a focus on defensive solidity.",
    weaknesses: "Toothless up front — just seven goals in 10 main-round qualifiers." },
  "Uruguay": { fifaRank: 17,
    summary: "The quarter-finals are the aim after an uneasy buildup.",
    strengths: "Bielsa-ball: relentless high pressing and chasing the ball at all times.",
    weaknesses: "Short of old scoring power, leaning on an out-of-form Darwin Nunez." },
  "France": { fifaRank: 1,
    summary: "Blessed with attacking talent that is the envy of the world — if the handbrake comes off.",
    strengths: "A remarkable front four, a strong back four and perhaps the tournament's deepest bench.",
    weaknesses: "Coaching caution, or really the challenge of fitting all the pieces together." },
  "Senegal": { fifaRank: 14,
    summary: "The Lions of Teranga arrive in good shape with a freshened attack and sturdy defence.",
    strengths: "A more flexible approach and pace in attack to trouble opponents.",
    weaknesses: "An unconvincing recent tournament record outside the last Cup of Nations." },
  "Iraq": { fifaRank: 57,
    summary: "Here after a marathon 21-game qualifying journey, out to prove they belong.",
    strengths: "Nothing to lose — the pressure sits on the group's other three.",
    weaknesses: "Not free-scoring; breaking down three tough defences will be hard." },
  "Norway": { fifaRank: 31,
    summary: "Golden-generation vibes around Haaland, with effectiveness prized over aesthetics.",
    strengths: "Haaland leading a side that averaged nearly five goals a game in qualifying.",
    weaknesses: "A tough group demands a fast start, and the first-choice keeper has barely played." },
  "Argentina": { fifaRank: 3,
    summary: "World Cup and Copa America holders — familiar faces, but not all at peak fitness.",
    strengths: "Almost all of the 2022 winners remain, Messi included.",
    weaknesses: "Several players carried injury setbacks after demanding club seasons." },
  "Algeria": { fifaRank: 28,
    summary: "One of the World Cup's great unknowns after a qualifying cakewalk against weak opposition.",
    strengths: "Abundant technical ability, with Afcon showing their ceiling.",
    weaknesses: "The Afcon quarter-final collapse to Nigeria lingers — aberration or warning?" },
  "Austria": { fifaRank: 23,
    summary: "A high-pressing unit that knows itself, built on familiarity and collective movement rather than stars.",
    strengths: "Years of continuity have let the approach bed in fully.",
    weaknesses: "Any slip in structure exposes them, and Baumgartner's pre-tournament injury hurts." },
  "Jordan": { fifaRank: 63,
    summary: "A first-ever finals, reached with a game to spare, likely to sit deep in a back five.",
    strengths: "Quick transitions and the pace of star winger Al-Tamari.",
    weaknesses: "Al-Naimat's injury leaves a hole up top, and big-game experience is thin." },
  "Portugal": { fifaRank: 5,
    summary: "One last hurrah for Ronaldo, with the Nations League winners carrying real quality and ambition.",
    strengths: "A settled core with varied, versatile options and a collective mission after mourning Jota.",
    weaknesses: "Few, though Ronaldo's outsized influence is an ever-present risk." },
  "DR Congo": { fifaRank: 45,
    summary: "A pragmatic, detail-obsessed Leopards side with a clear collective identity.",
    strengths: "Extremely hard to break down and mentally tough, as their qualifying showed.",
    weaknesses: "Rarely dominate or create freely, with prep disrupted by an Ebola outbreak." },
  "Uzbekistan": { fifaRank: 50,
    summary: "A historic first World Cup, sticking with the 5-2-3 that powered qualifying.",
    strengths: "A solid defence including Khusanov, with just seven conceded in 10 games.",
    weaknesses: "Scoring is likely to be a struggle." },
  "Colombia": { fifaRank: 13,
    summary: "An experienced side after a rollercoaster qualifying — beating Brazil and Argentina, losing to Bolivia.",
    strengths: "Goals shouldn't be an issue, with Suarez prolific and only Argentina scoring more in qualifying.",
    weaknesses: "Tournament football won't forgive their habitual inconsistency." },
  "England": { fifaRank: 4,
    summary: "Cruised through a soft qualifying group — the usual question is how they handle the best in a knockout.",
    strengths: "Enviable attacking options, a glut of No 10s and Rice among the world's best midfielders.",
    weaknesses: "Question marks over defensive options and the usual fitness worries over key men." },
  "Croatia": { fifaRank: 11,
    summary: "Semi-finalists in 2018 and 2022, likely reverting to a back four.",
    strengths: "Bags of experience and a winning mentality, with Modric still pulling strings.",
    weaknesses: "An ageing core with plenty of miles in the legs facing sapping heat." },
  "Ghana": { fifaRank: 73,
    summary: "Loaded with attacking talent and breezed through qualifying, though recent defeats are a concern.",
    strengths: "A major set-piece threat, with in-form Semenyo among Europe's most dangerous attackers.",
    weaknesses: "A shortage of elite defenders and an inexperienced goalkeeping unit." },
  "Panama": { fifaRank: 33,
    summary: "La Marea Roja hope to improve on a hapless 2018 after long development.",
    strengths: "A long-settled, confident squad with pace and solid recent Gold Cup and Nations League runs.",
    weaknesses: "Tend to struggle against bigger teams, with several key players into their 30s." },
};
